services:
  - docker:dind

stages:
  - test
  - deploy

lint:
  stage: test
  image: node:11
  script:
    - cd frontend
    - npm i
    - npm i -g @angular/cli
    - ng lint
  allow_failure: true

test:
  stage: test
  image: docker
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - cd docker
    - docker-compose build
    - docker-compose run -e MASTER_KEY rails bash scripts/tests.sh
    
deploy-rails:
  image: ruby:2.5.3
  stage: deploy
  only:
    refs:
      - master
  variables:
    HEROKU_APP_NAME: afterworker
  before_script:
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update
    - apt-get install -y heroku-toolbelt
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    - heroku run rails db:migrate --exit-code --app afterworker

deploy-rt-service:
  image: ruby:2.5.3
  stage: deploy
  only:
    refs:
      - master
  variables:
    HEROKU_APP_NAME: afterworker-realtime
  before_script:
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update
    - apt-get install -y heroku-toolbelt
    - gem install dpl
  script:
    - cd rt-service
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY