image: docker

services:
  - docker:dind

stages:
  - test
  - deploy
    
test:
  stage: test
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - cd docker
    - docker-compose run rails rspec
    
deploy:
  image: ruby:2.5.3
  stage: deploy
  only:
    refs:
      - master
  variables:
    HEROKU_APP_NAME: afterworker
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
