version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=afterworker
      - POSTGRES_USER=afterworker
      - POSTGRES_PASSWORD=afterworker

  rails:
    build:
      context: ..
      dockerfile: ./docker/rails/Dockerfile
    container_name: docker_rails
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ..:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  mongodb:
    image: mongo:4
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: afterworker
      MONGO_INITDB_ROOT_PASSWORD: afterworker
      MONGO_INITDB_DATABASE: afterworker

  express:
    image: node:11
    volumes:
      - ../rt-service:/app
    environment:
      - PORT=8080
    command: bash -c "cd /app && npm i && npm start"
    ports:
      - 8080:8080
    depends_on:
      - rails
      - mongodb